# Site settings
title: CoffeeGrind
name: CoffeeGrind
email: hello@coffeegrind.io
description: > # this means to ignore newlines until "baseurl:"
  The time-keeping app that just works.
baseurl: ""
url: "http://coffeegrind.io"
